server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.10.10
###aliyun:
 #sms:
  # accessKeyId: LTAI4FiU7zsbdQsnrdkJUkBo
   #accessKeySecret: cqygjiQ8u3fU7uT34QbFiHGOV8KCch
  # template_code: SMS_180047713
  # sign_name: 小朱
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
 instance:
    prefer-ip-address: true